User.create! ([
  { firstname:"Grzegorz", lastname:"Brzeczyszczykiewicz", email:"contact@brzeczyszczykiewicz.com", password: "12345678" },
  { firstname:"John", lastname:"Doe", email:"johndoe@example.com", password: "12345678" },
  { firstname:"Nicole", lastname:"Cruchot", email:"nicole@mail.saintropez.fr", password: "12345678" },
  { firstname:"Ludovic", lastname:"Cruchot", email:"ludoviccruchot@gendarmerie.fr", password: "12345678" },
  { firstname:"Biggus", lastname:"Pomponus", email:"b_pomponus@legiox.rome", password: "12345678" },
  { firstname:"Incontinentia", lastname:"Morales", email:"incontinentia@rome.anc", password: "12345678" }
   ])

Category.create!([{ name: "Bikes" },{ name: "Parts" }, { name: "Clothing" }, { name: "Accessories" }, { name: "Nutrition" }, { name: "Protection"}])

category = Category.find_by(name:"Bikes")
category.products.create!(title:"Single Speed", description:"A single-speed bicycle is a type of bicycle with a single gear ratio. These bicycles are without derailleur gears, hub gearing or other methods for varying the gear ratio of the bicycle.
There are many types of modern single speed bicycles; BMX bicycles, most bicycles designed for children, cruiser type bicycles, classic commuter bicycles, unicycles, bicycles designed for track racing, fixed-gear road bicycles, and single speed mountain bicycles.
The fixed-gear single-speed bicycle is the most basic type of bicycle. A fixed-gear bike does not have a freewheel mechanism to allow coasting.", price: 299.99, user_id: 1)
category.products.create!(title:"Road bike", description:"A racing bicycle, also known as a road bike, is a bicycle designed for competitive road cycling, a sport governed by according to the rules of the Union Cycliste Internationale (UCI). The UCI rules were altered in 1934 to exclude recumbent bicycles. The most important characteristics about a racing bicycle are its weight and stiffness which determine the efficiency at which the power from a rider's pedal strokes can be transferred to the drive-train and subsequently to its wheels. To this effect racing bicycles may sacrifice comfort for speed. The drop handlebars are positioned lower than the saddle in order to put the rider in a more aerodynamic posture. The front and back wheels are close together so the bicycle has quick handling. The derailleur gear ratios are closely spaced so that the rider can pedal at their optimum cadence. Other racing bicycles, especially those used in time trialling, prioritize aerodynamics over comfort. ", price: 399.99, user_id: 1)
category.products.create!(title:"Mountain bike", description:"A mountain bike or mountain bicycle (abbreviated MTB or ATB, for all-terrain bicycle) is a bicycle created for off-road cycling.
Mountain bikes are typically ridden on mountain trails, fire roads, logging roads, and other unpaved environments. These types of terrain commonly include rocks, washouts, ruts, loose sand, loose gravel, roots, and steep grades (both inclines and declines). Mountain bikes are built to handle this terrain and the obstacles that are found in it like logs, vertical drop offs, and smaller boulders.
Mountain bike construction differs from a typical bicycle in many ways. The most noticeable differences are the inclusion of suspension on the frame and fork, larger knobby tires, more durable heavy duty wheels, more powerful brakes, and lower gear ratios needed for steep grades with poor traction.", price: 299.99, user_id: 1)
category.products.create!(title:"Time Trial bike", description:"A time trial bicycle is a racing bicycle designed for use in an individual or team time trials raced on roads. Special time trial bikes also exist for use in a velodrome.
Since the cyclist in a time trial is not permitted to draft (ride in the slipstream) behind other cyclists, reducing aerodynamic drag of the bicycle and rider is critical. One difference between a time trial bicycle and a road bicycle is the use of triathlon handlebars or aerobars. The main part of the bullhorns curves forward (like a road handlebar), but where the road handle bar curves down, the time trial bar ends. This provides a low tucked position that is aerodynamic while providing good stability. The time trial bar also uses a clip on bar or aerobar which attaches to the main bar near the stem and provides a position where the hands and fore-arms are close together, low and forward, providing a very aerodynamic (though less stable) position. The aerobar became popular when in 1989 Greg LeMond made up 50 seconds to defeat Laurent Fignon (the race leader) in the final stage (and final time trial) of the Tour de France. Time trial races tend to be much shorter than road races, so comfort is less of an issue. Also, control of the bike is less important, since there is little chance of bumping another rider and the courses tend to be less technical with little hill climbing, turns or descents.", price: 299.99, user_id: 1)
category.products.create!(title:"Bmx bike", description:"A BMX bike is an off-road sport bicycle used for racing and stunt riding. BMX means bicycle motocross.", price: 299.99, user_id: 1)

category = Category.find_by(name:"Parts")
category.products.create!(title:"Clipless Pedals", description:"Maximum performace", price: 299.99, user_id: 2)
category.products.create!(title:"Sadle", description:"Comfy sadle", price: 399.99, user_id: 2)
category.products.create!(title:"Chain", description:"Light and durable", price: 299.99, user_id: 2)
category.products.create!(title:"Wheels", description:"Carbon based ultra light", price: 299.99, user_id: 2)
category.products.create!(title:"Handlebar", description:"Compact Handlebar and steam.", price: 299.99, user_id: 2)

category = Category.find_by(name:"Clothing")
category.products.create!(title:"Shorts", description:"Upro men's compression bib shorts feature engineered gradient compression to accelerate blood flow and enhance oxygen delivery to your active muscles – boosting your power on the flats and stamina in the hills.", price: 299.99, user_id: 3)
category.products.create!(title:"Jersey", description:"Cycling jersey with attractive design, long zipper and three backpockets. 100% Poliester", price: 39.99, user_id: 3)
category.products.create!(title:"Gloves", description:"Gel hook cycling gloves with anti-shock padding.", price: 19.35, user_id: 3)
category.products.create!(title:"Jacket", description:"Made from wind resistant and breathable nylon with one waterproof pocket. With a host of other features this is an impressive weather enduring jacket.", price: 65.99, user_id: 1)
category.products.create!(title:"Tights", description:"The fabric has stretch so movement is not restricted and the lightly brushed inner surface gives just the right amount of warmth and wicking. Rear panels aid fit and breathability.", price: 99.99, user_id: 2)
category.products.create!(title:"Leg Warmers", description:"A brushed fleecy lined warmer that offers full protection from the cold. Silicone grippers keep the warmer in place.", price: 35.49, user_id: 3)

category = Category.find_by(name:"Accessories")
category.products.create!(title:"Bag", description:"Sleek, aero shape wedge pack for carrying tools, food, wallet, keys, maps, spare tubes, mini pump, and anything else you need to carry. Aerodynamic styling with traditional strap mount.", price: 17.49, user_id: 3)
category.products.create!(title:"Camera", description:"Very easy to use, bombproof and high quality video! Multiple mounting options as well make this one very versatile camera.", price: 199.99, user_id: 3)
category.products.create!(title:"Light", description:"Up to 300 lumen out-put in a lightweight, durable CNC machined aluminium body with side visibility cuts and MOR Optics. Never get left in the dark, the Intelligent Power Indicator button allows the user to check the power level at any time. Simple to use, Micro USB cable for USB recharging of the built-in Li-ion battery. Easily mounted with no tools required, fits a wide range of handlebar diameters via a snap-fit Composite Matrix mount that is secured with a multi -position, silicon strap.", price: 59.99, user_id: 3)
category.products.create!(title:"Pump", description:"A precision high-pressure floor pump, steel barrel and piston, varnished wood handle, and connectors. 130cm rubber hose easily reach both Presta and Schrader valves. Oversized gauge is precise and easy to read. The steel barrel is painted, making this pump stylish and durable.", price: 33.99, user_id: 1)
category.products.create!(title:"Water Bottle Cage", description:"Used by more Champions than any other cage of the past decade. Glass fibre-reinforced polyamide construction is durable, supple and attractive. Adjustable elastomer rubber, adapts to bottle shapes and absorbs vibration", price: 19.99, user_id: 2)

category = Category.find_by(name:"Nutrition")
category.products.create!(title:"Energy bar", description:"Whole, all-natural, organic ingredients. Good nutrition. And great taste. Whether you’re on a 150-mile bike ride or making your way through a long day, it’s the energy bar for everyone.", price: 20.99, user_id: 2)
category.products.create!(title:"Energy gel", description:"EnergyGel is smooth with a light consistency and a dash of real juice for a great taste. It’s not thick or overly sweet. Easy to open and swallow, each sachet contains 23g of carbohydrate. EnergyGel is award-winning and proven in many of the World’s toughest competitions.", price: 19.99, user_id: 3)
category.products.create!(title:"Electrolyte drink", description:"It produces a clean-tasting and highly refreshing drink with zero calories. The tabs contain light natural flavours with no artificial colours or preservatives. Drink contains Vitamin C and 5 electrolytes, including sodium, magnesium and potassium. ", price: 6.99, user_id: 1)
category.products.create!(title:"Hight protein recovery drink", description:"Whole, all-natural, organic ingredients. Good nutrition. And great taste. Whether you’re on a 150-mile bike ride or making your way through a long day, it’s the energy bar for everyone.", price: 41.19, user_id: 2)

category = Category.find_by(name:"Protection")
category.products.create!(title:"Helmet", description:"This lightweight, fully encapsulated all-mountain helmet utilizes maximum coverage and dimension to keep you safe and protected in all riding conditions. Whether you're charging single track, riding dirt jumps or grinding out miles on the XC bike, the helmet offers the premium fit, protection and style you want.", price: 58.49, user_id: 3)
category.products.create!(title:"Body armour", description:"Anatomical design provides a close fit while integrated zones protect the chest, ribs, back, clavicle, shoulders and biceps.", price: 399.99, user_id: 3)
category.products.create!(title:"Googles", description:"Clear lenses are enhanced with F3 anti-fog treatment, the optics maximize your range of peripheral and downward view. You can’t stay focused without comfort, so we engineered triple-layer face foam to wick away sweat, and strap outriggers for balanced pressure distribution. And to keep the strap from sliding, we treated it with silicone. This goggle also comes with a removable nose guard .", price: 65.15, user_id: 2)

# BIKES
product = Product.find_by(title:"Single Speed")
product.reviews.create!(content:"Such a great bike!", rating: 5, user_id: 6)
product.reviews.create!(content:"old school, yeah!", rating: 4, user_id: 5)
product.reviews.create!(content:"Just received this bike last week. This bike is awesome.", rating: 5, user_id: 2)
product.reviews.create!(content:"Praesent viverra convallis mi in adipiscing.", rating: 2, user_id: 1)
product.reviews.create!(content:"Sed diam magna, iaculis a facilisis et, hendrerit nec risus.", rating: 1, user_id: 6)
product.reviews.create!(content:"Quisque nec tempor augue, ut semper leo.", rating: 5, user_id: 4)
product.reviews.create!(content:"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 3, user_id: 2)
product.reviews.create!(content:"Cras a nisi nec lacus placerat vehicula.", rating: 5, user_id: 1)
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 5, user_id: 4)
product.reviews.create!(content:"Suspendisse posuere orci vitae rhoncus luctus. Quisque pellentesque aliquet orci ac ultrices.", rating: 3, user_id: 5)

product = Product.find_by(title:"Road bike")
product.reviews.create!(content:"This is one of the best, and well rounded race bikes I have ever ridden. This is one you should look at while they last.", rating: 5, user_id: 3)
product.reviews.create!(content:"Integer mollis euismod condimentum.", rating: 1, user_id: 6)
product.reviews.create!(content:"Fusce mi orci, tempor nec molestie vel, accumsan vitae dui.", rating: 3, user_id: 1)
product.reviews.create!(content:"Proin tempor elit vitae suscipit ullamcorper. Cras aliquam metus at vehicula sagittis.", rating: 4, user_id: 3)
product.reviews.create!(content:"Morbi convallis eget dui sed hendrerit. Nam aliquet, tellus in consectetur ullamcorper, neque nunc vulputate velit, eu posuere arcu sapien a justo.", rating: 5, user_id: 3)
product.reviews.create!(content:"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 3, user_id: 6)
product.reviews.create!(content:"Cras a nisi nec lacus placerat vehicula.", rating: 5, user_id: 3)
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 2, user_id: 4)
product.reviews.create!(content:"Suspendisse posuere orci vitae rhoncus luctus. Quisque pellentesque aliquet orci ac ultrices.", rating: 1, user_id: 6)

product = Product.find_by(title:"Mountain bike")
product.reviews.create!(content:"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In porta, lorem vitae fringilla mollis, massa felis ullamcorper quam, quis mollis dolor odio at orci.", rating: 5, user_id: 3)
product.reviews.create!(content:"Donec in erat ullamcorper, ornare nisi in, cursus eros.", rating: 1, user_id: 1)
product.reviews.create!(content:"Nullam convallis enim a ipsum viverra, sit amet rhoncus purus auctor. Ut interdum metus erat, vitae elementum orci fermentum eu.", rating: 2, user_id: 5)
product.reviews.create!(content:"In molestie sem aliquet, sollicitudin massa viverra, adipiscing orci. Quisque ullamcorper varius adipiscing.", rating: 2, user_id: 6)
product.reviews.create!(content:"In at diam ligula. Etiam quam risus, fringilla ut lacus et, volutpat porttitor dui. Integer diam velit, euismod sit amet porta in, vulputate in neque.", rating: 5, user_id: 4)
product.reviews.create!(content:"Phasellus ullamcorper elit fermentum semper adipiscing. Suspendisse at dolor dictum purus vestibulum ornare in eget tortor.", rating: 2, user_id: 3)

product = Product.find_by(title:"Mountain bike")
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 1, user_id: 4)
product.reviews.create!(content:"Suspendisse posuere orci vitae rhoncus luctus. Quisque pellentesque aliquet orci ac ultrices.", rating: 5, user_id: 6)
product.reviews.create!(content:"Phasellus fermentum venenatis tellus hendrerit sollicitudin.", rating: 3, user_id: 2)
product.reviews.create!(content:"Phasellus mauris neque, ullamcorper at arcu quis, porta venenatis arcu.", rating: 4, user_id: 3)

product = Product.find_by(title:"Time Trial bike")
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 4, user_id: 3)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 4)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 2, user_id: 6)
product.reviews.create!(content:"Suspendisse potenti. Mauris vehicula ultricies diam. Fusce et nisi non risus lobortis aliquet.", rating: 3, user_id: 3)
product.reviews.create!(content:"Proin iaculis ultricies dictum. Pellentesque gravida, sapien ac rhoncus luctus, tortor odio elementum est, ut vestibulum purus nibh eu eros.", rating: 5, user_id: 3)

product = Product.find_by(title:"Bmx bike")
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 1, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 4, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 2, user_id: 5)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 5, user_id: 4)
product.reviews.create!(content:"Fusce lobortis lobortis dolor, a euismod nulla rutrum quis. Fusce aliquet convallis tristique.", rating: 4, user_id: 6)


# PARTS
product = Product.find_by(title:"Clipless Pedals")
product.reviews.create!(content:"Fusce lobortis lobortis dolor, a euismod nulla rutrum quis.", rating: 1, user_id: 5)
product.reviews.create!(content:"Fusce aliquet convallis tristique. Fusce mollis erat in rutrum tincidunt.", rating: 4, user_id: 6)
product.reviews.create!(content:"Donec auctor mauris nec risus egestas, at aliquet felis tincidunt.", rating: 3, user_id: 3)
product.reviews.create!(content:"Donec quis magna rhoncus tortor mattis sodales in ut arcu. Aenean consequat elit sed dapibus tincidunt.", rating: 5, user_id: 4)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 4, user_id: 3)

product = Product.find_by(title:"Sadle")
product.reviews.create!(content:"Fusce id erat sodales, lobortis ante eu, rhoncus purus.", rating: 4, user_id: 4)
product.reviews.create!(content:"Cras a nisi nec lacus placerat vehicula.", rating: 1, user_id: 3)
product.reviews.create!(content:"Duis ultricies arcu sit amet urna sagittis, vel dapibus urna suscipit. Aliquam lacinia fermentum blandit.", rating: 2, user_id: 1)
product.reviews.create!(content:"FPellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 3, user_id: 3)
product.reviews.create!(content:"Nam eget elit tincidunt, faucibus libero eu, interdum neque. Quisque non velit vel ante lobortis viverra nec ut augue.", rating: 2, user_id: 4)
product.reviews.create!(content:"Nullam eu ultricies enim, vitae lacinia nibh.", rating: 5, user_id: 5)

product = Product.find_by(title:"Chain")
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 1, user_id: 2)
product.reviews.create!(content:"Fusce id erat sodales, lobortis ante eu, rhoncus purus.", rating: 1, user_id: 2)
product.reviews.create!(content:"Ut imperdiet dui sed lacinia ultricies. Duis ac porta risus. Maecenas volutpat eleifend est, in eleifend mi.", rating: 2, user_id: 6)
product.reviews.create!(content:"Etiam quam magna, vulputate a pulvinar ut, feugiat ac sapien. Nulla molestie non dui ut fermentum.", rating: 3, user_id: 2)

product = Product.find_by(title:"Wheels")
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 3, user_id: 4)
product.reviews.create!(content:"Fusce id erat sodales, lobortis ante eu, rhoncus purus.", rating: 5, user_id: 2)
product.reviews.create!(content:"Duis ultricies arcu sit amet urna sagittis, vel dapibus urna suscipit. Aliquam lacinia fermentum blandit.", rating: 2, user_id: 6)
product.reviews.create!(content:"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 4, user_id: 3)
product.reviews.create!(content:"Nam eget elit tincidunt, faucibus libero eu, interdum neque. Quisque non velit vel ante lobortis viverra nec ut augue.", rating: 4, user_id: 4)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 1)

product = Product.find_by(title:"Handlebar")
product.reviews.create!(content:"Donec quis magna rhoncus tortor mattis sodales in ut arcu. Aenean consequat elit sed dapibus tincidunt.", rating: 4, user_id: 4)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 5, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 4, user_id: 6)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 2, user_id: 5)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 2, user_id: 4)
product.reviews.create!(content:"Duis ultricies arcu sit amet urna sagittis, vel dapibus urna suscipit. Aliquam lacinia fermentum blandit.", rating: 2, user_id: 1)
product.reviews.create!(content:"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 1, user_id: 3)

#Clothing
product = Product.find_by(title:"Gloves")
product.reviews.create!(content:"Duis ac dapibus erat. Aliquam odio ante, fringilla vitae felis id, rutrum volutpat purus.", rating: 3, user_id: 6)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 4, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 2, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 1, user_id: 6)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 5, user_id: 4)
product.reviews.create!(content:"Maecenas in eleifend felis. Maecenas volutpat lobortis varius.", rating: 4, user_id: 3)

product = Product.find_by(title:"Jacket")
product.reviews.create!(content:"Sed sagittis tellus et turpis posuere, sit amet pretium ipsum tempus. Quisque eu sollicitudin ante.", rating: 1, user_id: 3)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 5, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 2, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 4, user_id: 5)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 3, user_id: 4)
product.reviews.create!(content:"Sed ligula justo, venenatis vel enim in, rutrum pharetra tortor. Morbi laoreet mattis risus. Curabitur et nisl nisl.", rating: 1, user_id: 3)

product = Product.find_by(title:"Tights")
product.reviews.create!(content:"Nulla imperdiet turpis vitae augue adipiscing ullamcorper.", rating: 2, user_id: 3)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 2, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 5, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 3, user_id: 6)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 4, user_id: 4)
product.reviews.create!(content:"Donec in est bibendum eros eleifend condimentum in bibendum arcu.", rating: 2, user_id: 3)

product = Product.find_by(title:"Leg Warmers")
product.reviews.create!(content:"Mauris lectus urna, rhoncus ac rhoncus id, sollicitudin ut sem. Pellentesque sed est in urna luctus imperdiet nec ut metus.", rating: 2, user_id: 5)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 5, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 3, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 5)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 4, user_id: 4)
product.reviews.create!(content:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.", rating: 4, user_id: 3)

# Accessories
product = Product.find_by(title:"Bag")
product.reviews.create!(content:"Nunc sed enim ullamcorper, ultrices sem sed, placerat tellus. Aenean lacinia orci massa, eu posuere erat vulputate in.", rating: 4, user_id: 1)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 5, user_id: 6)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 3, user_id: 2)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 2, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 4, user_id: 5)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 5, user_id: 4)
product.reviews.create!(content:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.", rating: 2, user_id: 3)

product = Product.find_by(title:"Camera")
product.reviews.create!(content:"Mauris lectus urna, rhoncus ac rhoncus id, sollicitudin ut sem. Pellentesque sed est in urna luctus imperdiet nec ut metus.", rating: 2, user_id: 2)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 3, user_id: 1)
product.reviews.create!(content:"Nunc sed enim ullamcorper, ultrices sem sed, placerat tellus. Aenean lacinia orci massa, eu posuere erat vulputate in.", rating: 5, user_id: 1)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 4, user_id: 6)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 5, user_id: 2)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 4, user_id: 4)
product.reviews.create!(content:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.", rating: 5, user_id: 3)

product = Product.find_by(title:"Light")
product.reviews.create!(content:"Mauris lectus urna, rhoncus ac rhoncus id, sollicitudin ut sem. Pellentesque sed est in urna luctus imperdiet nec ut metus.", rating: 3, user_id: 1)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 5, user_id: 1)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 2, user_id: 2)
product.reviews.create!(content:"Nunc sed enim ullamcorper, ultrices sem sed, placerat tellus. Aenean lacinia orci massa, eu posuere erat vulputate in.", rating: 2, user_id: 1)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 3, user_id: 6)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 4, user_id: 2)
product.reviews.create!(content:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.", rating: 3, user_id: 3)

product = Product.find_by(title:"Pump")
product.reviews.create!(content:"Mauris lectus urna, rhoncus ac rhoncus id, sollicitudin ut sem. Pellentesque sed est in urna luctus imperdiet nec ut metus.", rating: 3, user_id: 1)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 4, user_id: 1)
product.reviews.create!(content:"Nunc imperdiet metus eget tincidunt ornare. Phasellus sagittis risus ipsum, vel interdum dui varius in.", rating: 2, user_id: 6)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 3, user_id: 3)
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 5, user_id: 4)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 2, user_id: 4)
product.reviews.create!(content:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.", rating: 1, user_id: 3)

product = Product.find_by(title:"Water Bottle Cage")
product.reviews.create!(content:"Nunc imperdiet metus eget tincidunt ornare. Phasellus sagittis risus ipsum, vel interdum dui varius in.", rating: 3, user_id: 6)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 5, user_id: 3)
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 3, user_id: 4)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 4, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 5)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 4, user_id: 4)
product.reviews.create!(content:"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.", rating: 2, user_id: 3)

#Nutrition
product = Product.find_by(title:"Energy bar")
product.reviews.create!(content:"Nunc sed enim ullamcorper, ultrices sem sed, placerat tellus. Aenean lacinia orci massa, eu posuere erat vulputate in.", rating: 5, user_id: 1)
product.reviews.create!(content:"Praesent ut nunc non libero semper pellentesque. Aliquam fringilla nisl vitae augue convallis dapibus.", rating: 4, user_id: 6)
product.reviews.create!(content:"Vivamus ultrices, tellus at rutrum fermentum, arcu augue viverra justo, non fermentum ante felis vitae turpis.", rating: 2, user_id: 2)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 6)
product.reviews.create!(content:"Maecenas pretium bibendum nisl, sed mattis est posuere sollicitudin.", rating: 3, user_id: 4)
product.reviews.create!(content:"Pellentesque eleifend elit purus, ut porttitor enim commodo sit amet. Mauris sed feugiat quam.", rating: 1, user_id: 3)

product = Product.find_by(title:"Energy gel")
product.reviews.create!(content:"ras tincidunt diam eget dictum tempus. Nullam ultrices lacus nunc, sit amet auctor diam malesuada et.", rating: 4, user_id: 4)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 5, user_id: 3)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 4, user_id: 4)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 5, user_id: 5)
product.reviews.create!(content:"Vestibulum congue accumsan nibh lobortis luctus. Nullam sed ultrices lacus.", rating: 4, user_id: 3)

product = Product.find_by(title:"Electrolyte drink")
product.reviews.create!(content:"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 3, user_id: 1)
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 5, user_id: 6)
product.reviews.create!(content:"Suspendisse posuere orci vitae rhoncus luctus. Quisque pellentesque aliquet orci ac ultrices.", rating: 4, user_id: 5)
product.reviews.create!(content:"Phasellus fermentum venenatis tellus hendrerit sollicitudin.", rating: 4, user_id: 2)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 5, user_id: 5)
product.reviews.create!(content:"Mauris sed bibendum augue, scelerisque pulvinar nisi.", rating: 5, user_id: 3)

product = Product.find_by(title:"Hight protein recovery drink")
product.reviews.create!(content:"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.", rating: 4, user_id: 2)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 2, user_id: 3)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 4)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 5, user_id: 5)
product.reviews.create!(content:"Aenean tempor sit amet libero sit amet eleifend.", rating: 4, user_id: 3)
  
#Protection
product = Product.find_by(title:"Helmet")
product.reviews.create!(content:"Suspendisse vitae ultricies ante, imperdiet laoreet eros. Nam sapien sapien, cursus at urna vel, tempus pulvinar lorem.", rating: 3, user_id: 6)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 5, user_id: 3)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 4, user_id: 4)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 5, user_id: 5)
product.reviews.create!(content:"Fusce eget diam nec elit varius ullamcorper.", rating: 4, user_id: 3)

product = Product.find_by(title:"Body armour")
product.reviews.create!(content:"Nunc imperdiet metus eget tincidunt ornare. Phasellus sagittis risus ipsum, vel interdum dui varius in.", rating: 1, user_id: 6)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 3, user_id: 3)
product.reviews.create!(content:"Donec pellentesque laoreet velit, non malesuada lorem. Nullam sit amet tincidunt elit.", rating: 5, user_id: 4)
product.reviews.create!(content:"Suspendisse posuere orci vitae rhoncus luctus. Quisque pellentesque aliquet orci ac ultrices.", rating: 4, user_id: 5)
product.reviews.create!(content:"Phasellus fermentum venenatis tellus hendrerit sollicitudin.", rating: 5, user_id: 2)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 5, user_id: 6)
product.reviews.create!(content:"Curabitur at dui non nisi condimentum pulvinar sit amet ut arcu.", rating: 4, user_id: 3)

product = Product.find_by(title:"Googles")
product.reviews.create!(content:"Suspendisse sit amet pharetra dui. Aenean quis enim varius, consequat enim ut, convallis risus.", rating: 5, user_id: 4)
product.reviews.create!(content:"Vestibulum eget nunc euismod odio condimentum pharetra. Nullam id ipsum ut enim consectetur ornare.", rating: 4, user_id: 3)
product.reviews.create!(content:"Quisque et nisi velit. Integer lobortis id odio eget faucibus.", rating: 5, user_id: 4)
product.reviews.create!(content:"Maecenas in nunc sed dui venenatis blandit. Suspendisse semper rhoncus urna in sodales.", rating: 4, user_id: 5)
product.reviews.create!(content:"Vivamus tincidunt nisl ac nibh malesuada blandit. Proin at lacus sit amet turpis sagittis mattis quis id sapien.", rating: 5, user_id: 6)